=== Izzy1647/Web_Experiments/实验五/XSD/ex_5_17.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ex_5_17" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="booklist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ISBN" type="xs:string"/>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="authorlist" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="author" type="xs:string" maxOccurs="5"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="price" type="xs:decimal"/>
                        </xs:sequence>
                        <xs:attribute name="classify" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="社会科学"/>
                                    <xs:enumeration value="自然科学"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Izzy1647/Web_Experiments/实验五/XSD/ex_5_17.xml
<?xml version="1.0" encoding="utf-8"?>
<booklist xmlns="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ex_5_17.xsd">
    <book classify="自然科学">
        <ISBN>7-302-12066-8</ISBN>
        <title>JAVA实用教程</title>
        <authorlist>
            <author>Herbert Schildt</author>
            <author>马海军</author>
        </authorlist>
        <price>64.00</price>
    </book>
    <book classify="社会科学">
        <IBSN>7-5037-1978</IBSN>
        <title>投资学</title>
        <authorlist>
            <author>张中华</author>
            <author>谢进程</author>
        </authorlist>
        <price>19.00</price>
    </book>
</booklist>
